### PR TITLE
add basic window raising and fix alacritty error and change border colours on window focus

### PR DESCRIPTION
**Pull request by lyiriyah**
Basic window raising

### CODE REVIEW

**Comment by lyiriyah** [comment]
Getting weird error with alacritty: 
`[xcb] Unknown sequence number while processing queue`
`[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called`
`[xcb] Aborting, sorry about that.`
`alacritty: xcb_io.c:269: poll_for_event: Assertion '!xcb_xlib_threads_sequence_lost' failed.`
Will try to shoehorn fix in to this PR

**Comment by curlpipe** [comment]
I saw you were using the `xlib` library here.
I want to use the `xcb` library as much as possible, for consistency and for asynchronous reasons.

For the Alacritty fix, it seems there is no xcb equivalent fix, probably due to the design of the API, and sometimes there simply isn't an xcb equivalent fix, e.g. for retrieving the keyboard mappings, hence why there is an `xlib` dependency. Is this error fatal? If not, I do wander what we lose by ignoring it entirely. Perhaps `InitThreads` only really needs to be called if the WM used mainly xlib instead of xcb?

But for the window raising, there seems to be a way to lift a window above the other windows in xcb, using a call along the lines of 

```rust
xcb::configure_window(
	&self.conn, 
	window, 
	&[(xcb::CONFIG_WINDOW_STACK_MODE as u16, xcb::STACK_MODE_ABOVE)]
);
```

I really appreciate the PR :)

**Comment by lyiriyah** [comment]
I'll try it

**Comment by lyiriyah** [comment]
About the alacritty thing, alacritty won't launch when it occurs

**Comment by curlpipe** [comment]
Alacritty launches for me without this, but if this is a problem experienced by some, then that is good enough reason to keep that there. I don't think it is really that much of a burden anyway, as, just like the keyboard mapping call, is only run once at the start of the programs lifespan.

**Comment by lyiriyah** [comment]
Added border colours changing on focus

**Comment by lyiriyah** [comment]
I won't push to this branch any more lol

**Pull request merged**
